import platform, os
env = Environment()
env.Append( CPPDEFINES=['_ZPRBUILD'])

#ustawienia kompilatora visual studio 2013 (cl)
if(platform.system() == "Windows"):
    env.Append( CPPDEFINES=['_WINDOWS'])
    env.Append( CPPFLAGS = ' /EHsc /MD /W4 /I C:/boost_1_64_0 ' )
    env.Append( LIBS = ['pdh'] )

elif(platform.system() == "Linux"):
    env.Append( CPPDEFINES=['_LINUX'])
    env.Append( CPPFLAGS = '-Wall --std=c++11' )
    env.Append( LINKFLAGS = '-Wall --std=c++11' )

else:
    print platform.system() + " not supported"

env.SharedLibrary('ZprMonitor', ['src/ZprMonitor.cpp', 'src/RamDaemon.cpp', 'src/DaemonInterface.cpp', 'src/CpuDaemon.cpp', 'src/DaemonFactory.cpp'] )
