import platform, os
env = Environment()

#ustawienia kompilatora visual studio 2013 (cl)
if(platform.system() == "Windows"):
    env.Append( CPPDEFINES=['_WINDOWS'])
    env.Append( CPPFLAGS = ' /EHsc /MD /W4 ' )
    env.Program('testapp', ['src/testapp.cpp'] )

elif(platform.system() == "Linux"):
    env.Append( CPPDEFINES=['_LINUX'])
    env.Append( CPPFLAGS = '-pthread -Wall --std=c++11' )
    env.Append( LINKFLAGS = '-pthread -Wall --std=c++11' )
    env.Program('testapp', ['src/testapp.cpp'], LIBS=['dl', 'pthread'] )

else:
    print platform.system() + " not supported"

